// H1 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

init()
{

}

onplayerconnect()
{
    for (;;)
    {
        level waittill( "connected", var_0 );
        var_0 thread updatereflectionprobe();
    }
}

updatereflectionprobe()
{

}

reflectionprobebuttons()
{

}

gotonextspawn()
{

}

gotoprevspawn()
{

}

gotonextstartspawn()
{

}

gotoprevstartspawn()
{

}

monitortagnoteworthyevent()
{

}
